const{test}=require('node:test');const a=require('node:assert/strict');const M=require('./sim-model.js');
test('замена действует в полуоткрытом окне, очередь сохраняется',()=>{let s=M.createState();M.assign(s,{team:'api',person:'boris',start:12,end:16});s.hour=11;a.equal(M.coverage(s,'api').person,'anna');s.hour=12;a.equal(M.coverage(s,'api').person,'boris');s.hour=16;a.equal(M.coverage(s,'api').person,'anna');s.day=1;a.equal(M.coverage(s,'api').person,'boris');});
test('больничный не меняет расписание, но препятствует учебному ACK',()=>{let s=M.createState('sick');a.equal(M.coverage(s,'api').person,'anna');a.equal(M.ack(s),false);a.equal(M.assign(s,{team:'api',person:'boris',start:9,end:16}),true);a.equal(M.selected(s).owner,'anna');M.reroute(s);a.equal(M.selected(s).owner,'boris');M.ack(s);M.resolve(s);a.equal(M.complete(s),true);});
test('учебный маршрут: 0, 5, 15 минут; ACK останавливает',()=>{let s=M.createState('silent');M.step(s,4);a.equal(M.selected(s).owner,'anna');M.step(s,1);a.equal(M.selected(s).owner,'boris');M.step(s,10);a.equal(M.selected(s).owner,'ilya');M.ack(s);M.step(s,60);a.equal(M.selected(s).owner,'ilya');a.equal(M.selected(s).status,'ack');a.equal(M.coverage(s,'api').person,'anna');});
test('исчерпание маршрута не решает инцидент',()=>{let s=M.createState('silent');M.step(s,30);a.equal(M.selected(s).next,null);a.equal(M.selected(s).status,'firing');});
test('ошибка доставки не препятствует назначению',()=>{let s=M.createState('silent');s.delivery=false;M.step(s,5);a.equal(M.selected(s).owner,'boris');a.equal(M.selected(s).delivered,false);});
test('праздник в среду не активирует слой выходных',()=>{let s=M.createState('holiday');s.holiday=true;a.equal(M.coverage(s,'api').person,'anna');s.day=5;a.equal(M.coverage(s,'api').person,'ilya');});
test('явные смены: пробел, назначение, конфликт',()=>{let s=M.createState('slots');a.equal(M.coverage(s,'api').person,null);a.equal(M.assign(s,{team:'api',person:'boris',start:9,end:18,kind:'shift'}),true);a.equal(M.assign(s,{team:'api',person:'anna',start:10,end:11,kind:'shift'}),false);M.spawn(s,'api');a.equal(M.selected(s).owner,'boris');M.ack(s);M.resolve(s);a.equal(M.complete(s),true);});
test('недопустимые замены отклоняются',()=>{let s=M.createState();s.absent.boris=true;a.equal(M.assign(s,{team:'api',person:'boris',start:9,end:16}),false);a.equal(M.assign(s,{team:'api',person:'vera',start:9,end:16}),false);a.equal(M.assign(s,{team:'api',person:'anna',start:16,end:9}),false);});
test('пост на 2 места сохраняет очередь и передаёт её дальше',()=>{let s=M.createState('dispatch');M.spawn(s,'api');M.spawn(s,'data');M.spawn(s,'net');a.equal(M.selected(s).status,'queued');a.equal(M.selected(s).delivered,false);s.selected=1;M.handoff(s);a.equal(s.incidents[2].owner,'mira');a.equal(s.incidents[0].owner,'anna');for(let id=1;id<=3;id++){s.selected=id;if(M.selected(s).owner==='mira')M.handoff(s);M.ack(s);M.resolve(s);}a.equal(M.complete(s),true);});
test('смена архитектуры не переписывает существующий маршрут',()=>{let s=M.createState('silent');const before=JSON.stringify(M.selected(s));M.setArchitecture(s,'dispatch');a.equal(JSON.stringify(M.selected(s)),before);});

test('нет покрытия — нет доставки; ручное назначение восстанавливает адресата',()=>{let s=M.createState('slots');M.spawn(s,'api');a.equal(M.selected(s).owner,null);a.equal(M.selected(s).delivered,false);M.assign(s,{team:'api',person:'boris',start:9,end:18,kind:'shift'});M.reroute(s);a.equal(M.selected(s).delivered,true);});
